runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2  
env_variables:
  GOOGLE_CLOUD_PROJECT: "calculator-445320"  
  BUCKET_NAME: "flask-app-storage"     

handlers:
  - url: /.*
    script: auto
